### ISSUE TITLE
Possible to replace `randomcoloR` with some analogue or make it optional?

### ISSUE THREAD

**Issue by barracuda156** [stla/tessellation#1]
`randomcoloR` pulls in dependency on `V8`, which is a) a very heavy stuff to build and b) broken on some platforms.

**Comment by stla** [comment]
Hi,

This is just done 👍 

You firstly have to install the **colorsGen** package, which is not on CRAN yet:
```r
remotes::install_github("stla/colorsGen")
```
then the latest version of **tessellation**:
```r
remotes::install_github("stla/tessellation")
```

**Comment by barracuda156** [comment]
@stla Thank you very much! I can add `colorsGen` to Macports, and then `tessellation` too.

**Comment by barracuda156** [comment]
@stla Both ports now merged and available to install via `sudo port install R-colorsGen R-tessellation`
https://ports.macports.org/port/R-tessellation/details
https://ports.macports.org/port/R-colorsGen/details

**Comment by stla** [comment]
Yes, there are on CRAN now. We can close.

**Comment by barracuda156** [comment]
Thank you!
